version: "3"

services:

  api:
    build: .
    container_name: api
    restart: always
    command: bash -c "alembic upgrade head && uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./api:/app/api

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
